name: alis
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=10.2
  - pytorch=1.7.1
  - torchvision=0.8.2
  - opencv=4.5.2
  - pip:
    - hydra-core==1.0.6
    - click==7.1.2
    - scipy==1.6.1
    - ninja==1.10.0
    - tensorboard==2.4.1
    - tqdm==4.59.0
    - gitpython
    - gpustat
    - scikit-learn
    - -e .
